### PR TITLE
Resolves #27:  Admin password reset functionality now off by default.

### LINKED ISSUE #27: Admin password reset by default
So it appears that following a database import, by default, vampd-drupal will attempt to reset a password for a user by the name of "admin."  This is great if you're aware of this default functionality and you actually have a user with the username of "admin", but if you're not expecting it and don't have a user by that name in your Drupal DB it results in an error on spin-up.

Don't get me wrong - I think this functionality is awesome - but I'd suggest we turn it off by default and document how to use it (unless documentation is already present!) as one of the cool features of Vampd.

### PR DESCRIPTION
**Pull request by chrisolof**

### CODE REVIEW

**Comment by timodwhit** [comment]
Can you add documentation on the functionality. :-)

**Comment by timodwhit** [comment]
Does this make sense? https://github.com/vampd/drupal/wiki/Drupal-Users

**Comment by timodwhit** [comment]
@chrisolof can you update the readme with the latest defaults?

**Comment by timodwhit** [comment]
@chrisolof: If you take care of the README, we can get this in...

**Comment by chrisolof** [comment]
@timodwhit Readme is updated.

**Pull request merged**
